package de.muenchen.stadtbezirksbudget.backend.antrag.entity;

/**
 * Represents the information, in which status the corresponding Antrag currently is.
 */
public enum Status {
    EINGEGANGEN,
    WARTEN_AUF_BUERGERRUECKMELDUNG,
    VOLLSTAENDIG,
    SITZUNGSVORLAGE_ERSTELLT,
    SITZUNGSVORLAGE_UEBERMITTELT,
    BESCHLUSS_ERHALTEN,
    ZUWENDUNGSBESCHEID_ERSTELLT,
    ZUWENDUNGSBESCHEID_VERSENDET,
    VERWENDUNGSNACHWEISE_GEPRUEFT,
    AUSZAHLUNG,
    ABRECHNUNGSSCHREIBEN_ERSTELLT,
    RUECKZAHLUNG,
    ABGESCHLOSSEN,
    ABLEHNUNGSBESCHLUSS_ERHALTEN,
    ABLEHNUNGSBESCHEID_ERSTELLT,
    ABGELEHNT_VON_BA,
    ABGELEHNT_KEINE_RUECKMELDUNG,
    ABGELEHNT_NICHT_ZUSTAENDIG,
    ABGELEHNT_NICHT_FOERDERFAEHIG,
}
