<script lang="ts" setup>
import {sortOptionsByField} from "@/types/AntragListSort.ts";
import {useAntragListSort} from "@/composables/useAntragListSort.ts";

const {sortOption, resetSorting, updateSorting} = useAntragListSort();
</script>

<template>
  <v-card data-test="antrag-list-sort-card">
    <v-card-title>
      <v-row>
        <v-col class="d-flex align-center">Sortieren nach</v-col>
        <v-col cols="auto">
          <v-btn
              data-test="antrag-list-sort-reset-btn"
              variant="outlined"
              @click="resetSorting"
          >Sortierung zurücksetzen
          </v-btn>
        </v-col>
      </v-row>
    </v-card-title>
    <v-card-text>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('status')"
              :model-value="sortOption.status"
              clearable
              density="compact"
              hide-details="auto"
              label="Status"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('nummer')"
              :model-value="sortOption.nummer"
              clearable
              density="compact"
              hide-details="auto"
              label="Nummer"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('aktenzeichen')"
              :model-value="sortOption.aktenzeichen"
              clearable
              density="compact"
              hide-details="auto"
              label="Aktenzeichen"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('bezirk')"
              :model-value="sortOption.bezirk"
              clearable
              density="compact"
              hide-details="auto"
              label="Bezirk"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('antragsdatum')"
              :model-value="sortOption.antragsdatum"
              clearable
              density="compact"
              hide-details="auto"
              label="Antragsdatum"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('antragsteller')"
              :model-value="sortOption.antragsteller"
              clearable
              density="compact"
              hide-details="auto"
              label="Antragsteller/in"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('projekt')"
              :model-value="sortOption.projekt"
              clearable
              density="compact"
              hide-details="auto"
              label="Projekt"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('beantragtesBudget')"
              :model-value="sortOption.beantragtesBudget"
              clearable
              density="compact"
              hide-details="auto"
              label="Beantragtes Budget"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('art')"
              :model-value="sortOption.art"
              clearable
              density="compact"
              hide-details="auto"
              label="Art"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('aktualisierungArt')"
              :model-value="sortOption.aktualisierungArt"
              clearable
              density="compact"
              hide-details="auto"
              label="Aktualisierung"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-select
              :items="sortOptionsByField('aktualisierungDatum')"
              :model-value="sortOption.aktualisierungDatum"
              clearable
              density="compact"
              hide-details="auto"
              label="Datum Aktualisierung"
              return-object
              variant="underlined"
              @update:model-value="updateSorting"
          ></v-select>
        </v-col>
      </v-row>
    </v-card-text>
  </v-card>
</template>

<style scoped></style>
