name: 🛠️ Maintenance work
description: Suggest useful or required maintenance work for this project.
title: "🛠️ "
type: task
labels: ["🛠️ Maintenance"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this maintenance work issue!
        To expedite issue processing, please search open and closed issues before submitting a new one.
        Please read our [Code of Conduct](../blob/main/.github/CODE_OF_CONDUCT.md).
  - type: markdown
    attributes:
      value: "## General"
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description (optional)
      description: A clear and concise description of what the problem is (if related to problem)
    validations:
      required: false
  - type: textarea
    id: desired-solution
    attributes:
      label: Desired solution
      description: A clear and concise description of what you want to happen
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Considered alternatives (optional)
      description: A clear and concise description of any alternative solutions you've considered
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Extras"
  - type: textarea
    id: context
    attributes:
      label: Additional context (optional)
      description: Additional context (references, links, screenshots, ...) that might be helpful
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Definitions"
  - type: checkboxes
    id: DoR
    attributes:
      label: Definition of Ready (DoR)
      options:
        - label: Die User Story ist klar und verständlich formuliert.
        - label: Die Akzeptanzkriterien sind klar und verständlich formuliert.
        - label: Die User Story wurde geschätzt.
        - label: Die User Story wurde mit PO oder Ansprechperson aus dem Fachbereich besprochen.
  - type: checkboxes
    id: DoD
    attributes:
      label: Definition of Done (DoD)
      options:
        - label: Der Code wurde einem Peer-Review unterzogen.
        - label: Der Code wurde dokumentiert.
        - label: Die User Story ist vollständig umgesetzt und steht auf der Testumgebung zur Verfügung.
        - label: Die Umsetzung der Akzeptanzkriterien wurde durch PO oder Ansprechperson aus dem Fachbereich abgenommen.
  - type: markdown
    attributes:
      value: "## Confirmations"
  - type: checkboxes
    id: check-duplicate
    attributes:
      label: No duplicate
      description: By submitting this issue, you confirm to have checked for duplicate issues beforehand.
      options:
        - label: I confirm that this issue is not a duplicate
          required: true
  - type: checkboxes
    id: conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true