name: 📝 Documentation change
description: Suggest a documentation change for this project
title: "📝 "
type: task
labels: ["📝 Documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation change issue!
        To expedite issue processing, please search open and closed issues before submitting a new one.
        Please read our [Code of Conduct](../blob/main/.github/CODE_OF_CONDUCT.md).
  - type: markdown
    attributes:
      value: "## General"
  - type: dropdown
    id: component
    attributes:
      label: Relevant component
      multiple: true
      description: Name(s) of the affected component(s) (if applicable)
      options:
        - stadtbezirksbudget-frontend
        - stadtbezirksbudget-backend
        - stadtbezirksbudget-eai
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description (optional)
      description: A clear and concise description of what the problem is (if related to problem)
    validations:
      required: false
  - type: textarea
    id: desired-solution
    attributes:
      label: Desired solution
      description: A clear and concise description of what you want to happen
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Extras"
  - type: textarea
    id: context
    attributes:
      label: Additional context (optional)
      description: Additional context (references, links, screenshots, ...) that might be helpful
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Definitions"
  - type: checkboxes
    id: DoR
    attributes:
      label: Definition of Ready (DoR)
      options:
        - label: The user story is clearly and comprehensively formulated.
        - label: Acceptance criteria are clearly and comprehensively formulated
        - label: The user story was estimated.
        - label: The user story was discussed with the PO or contact person from the department.
  - type: checkboxes
    id: DoD
    attributes:
      label: Definition of Done (DoD)
      options:
        - label: The code has been peer reviewed
        - label: The code has been documented.
        - label: There is a UX design (decision) [may only be necessary for front-end tasks].
        - label: The user story has been fully implemented and is available on the test environment.
        - label: The implementation of the acceptance criteria was approved by the PO or the contact person from the department.
  - type: markdown
    attributes:
      value: "## Confirmations"
  - type: checkboxes
    id: check-duplicate
    attributes:
      label: No duplicate
      description: By submitting this issue, you confirm to have checked for duplicate issues beforehand.
      options:
        - label: I confirm that this issue is not a duplicate
          required: true
  - type: checkboxes
    id: conduct
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/main/.github/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true