spring:
  application:
    name: "@project.artifactId@"
    group: "@project.groupId@"
    version: "@project.version@"

server:
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    access:
      default: none
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - sbom
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
    info:
      access: read_only
    prometheus:
      access: read_only
    sbom:
      access: read_only
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

info:
  application:
    name: ${spring.application.name}
    version: ${spring.application.version}
    group: ${spring.application.group}
    description: "@project.description@"
  build:
    java.version: "@java.version@"
    spring-cloud.version: "@spring-cloud-dependencies.version@"

# Custom properties
output: direct:foo
